application: here-your-project-id
# Other settings here...
#instance_class: F4
#automatic_scaling:
#  min_pending_latency: 50ms
#  max_pending_latency: 200ms
version: development
runtime: php55
api_version: 1

handlers:

# Serve html & php  as script and /
- url: /(.+\.(html|php))$
  script: \1
  secure: always

# Serve images as static resources.
- url: /(.+\.(gif|png|jpg|css|ico|txt|htm|js))$
  static_files: \1
  upload: .+\.(gif|png|jpg|css|ico|txt|htm|js)$
  application_readable: true
  secure: optional

# Use cloudframework-io dispatcher.
- url: /.*
  script: vendor/cloudframework-io/core/src/main.php
  secure: always
